name: Build Vehicle Profiles

on:
  push:
    branches:
      - main
    paths:
      - 'vehicle_profiles/**'
      - '.vehicle_profiles/**'
      - '.github/workflows/vehicle_profiles.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: |
          cd .vehicle_profiles
          npm ci
          npm run build
          npx prettier ../vehicle_profiles --write
          npx prettier . --write
          cd -
      - name: Commit
        uses: EndBug/add-and-commit@v9
        with:
          author_name: Jay Oswald
          author_email: jay@oswald.net.au
          message: Commit from GitHub Actions (Build Vehicle Profiles)
          pull: '--rebase --autostash'
          push: true
